### ISSUE TITLE
import rln need to be updated

### ISSUE THREAD

**Issue by salikatt** [danielskaare/isurvey_tools#10]
The runline importer does not handle the different rln-type of files.

The files do have different header/no-header and separator.

**NaviModel rln export:**
>no header
> space delimiter

**HMD Classic (save as):**
>header using #
>name of runline using "name" - if created
>space delimiter

Excel isurvey tools:
>header using #
>name using "name"
>semicolon as delimiter (old EIVA method)

From excel:
![image](https://user-images.githubusercontent.com/60242151/75625844-2a51ac00-5bc2-11ea-800a-23df7342ccd8.png)

From HMD Classic
![image](https://user-images.githubusercontent.com/60242151/75625852-45242080-5bc2-11ea-8afb-9802981493ee.png)

From NaviModel:
![image](https://user-images.githubusercontent.com/60242151/75625864-579e5a00-5bc2-11ea-9587-6e20f7b6b11c.png)

**Comment by salikatt** [comment]
apparently pandas_read_csv does not include lines starting with # so no need to include line in skiplines parameter. Only need to handle if name is included, i.e "name" line.

Probably easiest to use a def function checking for any "name" lines

**Comment by salikatt** [comment]
the following read_csv: 
`df = pd.read_csv(file_path,  sep=' |;', skiprows=1, names=['easting', 'northing', 'kp'], engine='python')`

Using regex that handles space and ; as delimiter.

Only thing need to handle is the RPL name line, may need to use the ptyhon open readline funcitons to collect all the named lines. I may have some examples later.

**Comment by salikatt** [comment]
Great Daniel,
i see that you read the first 2 lines and skip if it of # or "" type, but what about runline with parallells/cross sections.  The different sections within the same runline should be created in the same feature file.
BTW, it's possible to create a dictionary or list of dataframes.

I also need to test whats happening when importing runlines without KP value even though the kp is inluded as column in pandas, i believe it goes all well but create null-data if emtpy.

Added different versions of files for test purposes.
[runlines.zip](https://github.com/danielskaare/isurvey_tools/files/4291656/runlines.zip)

**Comment by danielskaare** [comment]
When there is no KP it adds "Null" in that column.

Multiple runlines is not supported, I thought that RLN files could only support 1 runline and RLX was multiple runlines. I see that the RLX contains start/stop position and kp on one line. Also Eiva has introduced RLXP which is more of a XML format.
