### ISSUE TITLE
dialog boxes

### ISSUE THREAD

**Issue by salikatt** [danielskaare/isurvey_tools#3]
do prefer dialog boxes to be **adjustable** in size as it can be nice to read the full path by adjusting dialog box size.

original variant:
![small](https://user-images.githubusercontent.com/60242151/73947959-96f5c580-48f8-11ea-8db0-61bbb6fcea0b.png)

larger variant:
![large](https://user-images.githubusercontent.com/60242151/73947968-9b21e300-48f8-11ea-80b2-4b1986cc8666.png)

more boxes:
![masterfile_default](https://user-images.githubusercontent.com/60242151/73978227-36807b80-492c-11ea-90c4-5046e9a62e25.png)
![masterfile_large](https://user-images.githubusercontent.com/60242151/73978233-38e2d580-492c-11ea-909a-3d420eb186ee.png)

**Comment by danielskaare** [comment]
Fixed
