### ISSUE TITLE
Plugin-in meny struktur

### ISSUE THREAD

**Issue by salikatt** [danielskaare/isurvey_tools#7]
Bør man vurdere en iSURVEY meny, som et tillegg?

iSurvey
|--Masterfile: 
|----> masterfile dialog
|----> Matplotlib canvas
|--import RLN: -> rpl dialog
|--import blabla: -> blabla dialog
|--export WP2: -> WP2 dialog
|--export DIS: -> display line dialog

Vi kan kanskje diskutere hvilke importer/eksporter som vi har behov for?

MMQGIS kan være en fin plugin for å se oppbygging. 
En annen interessant plugin å få inspirasjon fra er Midvattn. De jobber med spatiallite DB.

**Comment by danielskaare** [comment]
![image](https://user-images.githubusercontent.com/60060543/74870673-68490780-535a-11ea-9027-33b161893e17.png)

Meny for ikona vil automatisk komme. Kan eventuelt legge til fleire menyar i vinduet som poppar opp

**Comment by salikatt** [comment]
toppers Daniel
